name: ePublisher Automation

# It's important to update the schedule depending on the number of projects in the contents of this repository.
# The NUMBER_OF_PROJECTS variable is equal to the number of files in /content/hashtags.
on:
  schedule:
    - cron: '0 0-23/3 * * *'   # Runs at 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00
    - cron: '30 1-23/3 * * *'  # Runs at 01:30, 04:30, 07:30, 10:30, 13:30, 16:30, 19:30, 22:30
  push:
    branches:
      - T-1398

env:
  NUMBER_OF_PROJECTS: 4  # Set this to the number of posts to publish or projects you have (currently 4 to run only for projects 0, 1, 2 and 3 from content folder)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set repository name environment variable
        run: echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run script
        env:
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_LONG_LIVED_ACCESS_TOKEN: ${{ secrets.FACEBOOK_LONG_LIVED_ACCESS_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_USER_ID: ${{ secrets.TWITTER_USER_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: python3 app/main.py

      - name: Commit logs and content files
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git add generated_content.log tweets.json
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Store generated content, tweet response data, and updated content files"
            git push


