name: ePublisher Automation

# It's important to update the schedule depending on the number of projects in the contents of this repository.
# The NUMBER_OF_PROJECTS variable should be set to post daily for each project.
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches:
      - main
      - development

env:
  NUMBER_OF_PROJECTS: 2  # Set this to the number of projects you have

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}  # Ensure this secret is set in your repository settings
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          INSTAGRAM_API_KEY: ${{ secrets.INSTAGRAM_API_KEY }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: python3 app/main.py
