name: ePublisher Automation

# It's important to update the schedule depending on the number of projects in the contents of this repository.
# The NUMBER_OF_PROJECTS variable should be set to post daily for each project.
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches:
      - main
      - development

env:
  NUMBER_OF_PROJECTS: 2  # Set this to the number of projects you have

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Node.js dependencies
        run: npm install
      - name: Run script
        env:
          FACEBOOK_APP_ID: \${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: \${{ secrets.FACEBOOK_APP_SECRET }}
          FACEBOOK_PAGE_ID: \${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_LONG_LIVED_ACCESS_TOKEN: \${{ secrets.FACEBOOK_LONG_LIVED_ACCESS_TOKEN }}
          TWITTER_API_KEY: \${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: \${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: \${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: \${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_USER_ID: \${{ secrets.TWITTER_USER_ID }}
          GITHUB_RUN_NUMBER: \${{ github.run_number }}
        run: python3 app/main.py
