name: ePublisher Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          FACEBOOK_API_KEY: ${{ secrets.FACEBOOK_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          INSTAGRAM_API_KEY: ${{ secrets.INSTAGRAM_API_KEY }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python3 app/main.py
